# h2
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blog8
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

blog:
  file:
    path: /Users/liqiwen/workspace/upload/